server:
  port: 3030
  servlet:
    context-path: "/api/v1"
spring:
  main:
    web-application-type: servlet
  datasource:
    url: "jdbc:mysql://localhost:3306/randomshit?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
    username: "root"
    password: "chiggisdead@123"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
